version: "3.9"

services:
  helpdesk-backend:
    env_file:
      - .env.sensitive
    build: ./back-end
    image: helpdesk-backend
    container_name: backend
    ports:
      - 8080:8080

  helpdesk-frontend:
    depends_on:
      - helpdesk-backend
    build: ./front-end
    image: helpdesk-frontend
    container_name: frontend
    ports:
      - 4444:80
