server:
  servlet:
    context-path: /helpdesk

logging:
  file:
    name: app.log
  level:
    com.training.helpdesk: DEBUG
  logback:
    rollingpolicy:
      clean-history-on-start: true

spring:
  profiles:
    active: dev
  application:
    name: Help Desk
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:tickets
    name: tickets
    username: sa
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mk.test.only@gmail.com
    password: LkzNtcnjdNjkmrj
    protocol: smtp
    properties:
      debug: true
      smtp:
        auth: true
        starttls.enable: true

jwt:
  secret: AllYourBaseAreBelongToUsNoException
  validity: 86400000

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        generate_statistics: true
---
spring:
  config:
    activate:
      on-profile: prod

