server:
  servlet:
    context-path: /helpdesk
logging:
  file:
    name: app.log
  level:
    com.training.helpdesk: DEBUG
  logback:
    rollingpolicy:
      clean-history-on-start: true
spring:
  profiles:
    default: dev
  application:
    name: Help Desk
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:tickets
    name: tickets
    username: sa
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      resolve-lazily: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    view-names: mail/*
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          from: ${SPRING_MAIL_USERNAME}
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
jwt:
  secret: ${JWT_SECRET:AllYourBaseAreBelongToUsNoException}
  validity: 86400000
app:
  frontend-endpoint: ${APP_FRONTENDENDPOINT:#{'http://localhost:4444'}}
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        format_sql: true
  mail:
    properties:
      mail:
        debug: true
---
spring:
  config:
    activate:
      on-profile: prod
