server:
  servlet:
    context-path: /helpdesk

logging:
  file:
    name: app.log
  level:
    com.training.helpdesk: DEBUG
  logback:
    rollingpolicy:
      clean-history-on-start: true

spring:
  profiles:
    active: dev
  application:
    name: Help Desk
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:tickets
    name: tickets
    username: sa
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 5MB
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    view-names: mail/*
  mail:
    host: smtp.gmail.com
    port: 587
    username: mk.test.only@gmail.com
    password: rmysrxfgwrgymnks
    protocol: smtp
    properties:
      mail:
        smtp:
          from: mk.test.only@gmail.com
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

jwt:
  secret: AllYourBaseAreBelongToUsNoException
  validity: 86400000

app:
  frontend-endpoint: http://localhost:4444

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  mail:
    properties:
      mail:
        debug: true
---
spring:
  config:
    activate:
      on-profile: prod
